apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w3xv2jm3e-go
  janus-idp.io/tekton: w3xv2jm3e-go
  backstage.io/kubernetes-id: w3xv2jm3e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w3xv2jm3e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
