apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w3xv2jm3e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w3xv2jm3e-go 
  name: w3xv2jm3e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w3xv2jm3e-go 
